Notebook: Add in Offline Checks Notebook
Esri/field-maps-scripts pull request #32
Opened 2024-12-27 02:05 UTC by lau13820

This notebook aims to help enterprise users take their maps offline who may not have access to the new offline checks in place on ArcGIS Online

2024-12-31 19:31 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
`This notebook uses python version 2.3.0.3` - we may want to consider some language here similar to Enterprise 10.7+ where we say it was tested with 2.3.0.3 - or it's compatible with 2.3.x or 2.3.+

2024-12-31 19:37 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
My want to consider not having a separate block for `Access your GIS Account -ArcGIS Online`

2024-12-31 19:48 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "This process assumes that you have publishing and editing privileges for the map and that you are using either Enterprise 10.7+ or ArcGIS Online. This notebook uses python version 2.3.0.3\n",
This notebook uses python version 2.3.0.3 - we may want to consider some language here similar to Enterprise 10.7+ where we say it was tested with 2.3.0.3 - or it's compatible with 2.3.x or 2.3.+

2024-12-31 20:03 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +  {
My want to consider not having a separate block for `Access your GIS Account -ArcGIS Online`

2024-12-31 20:04 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "#### Checking Basemaps for Offline Use\n",
> We will evaluate four key aspects.

Suggest listing the aspects in bullets

2024-12-31 20:06 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "5. Depcrecated Tile Base Maps URLs: Ensure you are not using basemaps with base url: `https://tiledbasemaps.arcgis.com/arcgis/rest/services`\n",
typo for Deprecated

2024-12-31 20:27 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "        `esriFieldTypeBigInteger`\n",
consider bulleted list here

2024-12-31 20:28 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "If any field has one of these types, it is not supported for offline use.\n",
suggest indent

2024-12-31 20:31 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "                    layer_errors.append(f\"{layer_title} is depcrecated\")\n",
typo on deprecated

2024-12-31 20:33 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "def check_tables(\n",
Extra whitespace/return and comma here? should be `check_tables( tables) -> str:`

2024-12-31 20:34 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "    item_urls = set()\n",
nice use of a set

2024-12-31 21:01 UTC, jake-maps commented on notebooks/Offline Checks.ipynb
> +    "offline_map = gis.content.get(MAP_ITEM_ID_TO_CHECK)"
suggest check to see if this item was found

2025-01-02 18:21 UTC, lau13820 commented on notebooks/Offline Checks.ipynb
> +    "#### Checking Basemaps for Offline Use\n",
Looks like I forgot to change four to five! Thank you @jake-maps !

2025-01-24 23:48 UTC, justincolville requested changes

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "enterprise_url = \"https://mydomain.esri.com/portal\""
a const?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "    service_list = [\n",
a const?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "deprecated_urls = [\n",
a const?
Does this need to be global or can it be defined in the consuming function `is_deprecated_basemap_urls`, similar to service_list?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "    return layer_type in [\n",
for consistency with service_list and deprecated_urls, should we define this as SUPPORTED_LAYER_TYPES and then use it?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "username = input()\n",
remove input based on Slack discussion

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "forbidden_sql_keywords = [\n",
const, and similar comment to above about should it be global?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "        if field[\"type\"] in [\n",
change to SUPPORTED_FIELD_TYPE?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "        elif op_layer[\"layerType\"] in [\n",
define and use a SUPPORTED_TILE_LAYER_TYPES const?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "def check_layers(layers) -> str:\n",
Is the return type correct?  Should it be a list of str?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "def check_tables(tables) -> str:\n",
Is the return type correct?  Should it be a list of str?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "def check_map(webmap) -> str:\n",
Is the return type correct?  Should it be a list of str?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "    layer_errors = list(dict.fromkeys(layer_errors))\n",
Is this needed?  Can we end up with duplicates?

2025-01-24 23:48 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "    table_errors = list(dict.fromkeys(table_errors))\n",
Is this needed?  Can we end up with duplicates?

2025-01-25 00:10 UTC, lau13820 commented on notebooks/Offline Checks.ipynb
> +    "deprecated_urls = [\n",
I'll put in the method! 👍

2025-01-25 00:12 UTC, lau13820 commented on notebooks/Offline Checks.ipynb
> +    "    return layer_type in [\n",
Sounds good !

2025-03-20 16:57 UTC, lau13820 commented
@justincolville @jake-maps ready for your final reviews! Thank you so much.

2025-03-25 18:51 UTC, justincolville requested changes

2025-03-25 18:51 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "def check_offline_typekeyword(map) -> bool:\n",
Should this always have a bool return value?

2025-03-25 18:51 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "    \"Your map is ready for offline!\""
Should this be a print statement?

2025-03-25 18:51 UTC, justincolville commented on notebooks/Offline Checks.ipynb
> +    "def is_export_enabled_vector_tile_layer(basemaplayer) -> bool:\n",
Should this always have a bool return value?

2025-03-25 18:58 UTC, lau13820 commented on notebooks/Offline Checks.ipynb
> +    "    \"Your map is ready for offline!\""
Yes, good catch. Thanks!

2025-03-25 19:02 UTC, lau13820 commented on notebooks/Offline Checks.ipynb
> +    "def check_offline_typekeyword(map) -> bool:\n",
Good catch. Fixed

2025-03-25 19:43 UTC, justincolville approved these changes

2025-03-25 19:44 UTC, merged