fix: Update generate pdf notebook and add in example yml
Esri/field-maps-scripts pull request #33
Opened 2024-12-30 21:21 UTC by lau13820

Updated generate pdf notebook with updated PIL library. Included new cartopy dependencies in a separate yml file for the user to use if they would like.

2025-01-22 13:26 UTC, jake-maps commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> -    "This example shows how to generate an HTML and PDF report for a specific feature layer. It demonstrates how to create a report that includes summary statistics, photos, maps, and attribute infor
> tree inventory layer

I would update text to point to the specific layer name, I deployed the solution and I think it's calling for `Trees_public/Trees`

2025-01-22 13:45 UTC, jake-maps commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> +    "    if gps_info is None:\n",
In my test of attaching a screenshot through the tree edit app, this if statement did not appear to be working.  I think removing it and wrapping everything in a try/catch then returning  `return (0, 0,dt.now())` if it fails

2025-01-22 13:48 UTC, jake-maps requested changes
couple of comments. 

I did not have any issues with PIL library with the `field-maps-scripts` environment with latests yml

2025-01-22 21:24 UTC, lau13820 commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> -    "This example shows how to generate an HTML and PDF report for a specific feature layer. It demonstrates how to create a report that includes summary statistics, photos, maps, and attribute infor
Good call! Thank you!

2025-01-22 21:38 UTC, lau13820 commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> +    "    if gps_info is None:\n",
Nice catch. Will do. Thank you Jake!

2025-01-23 12:58 UTC, jake-maps commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> -    "This example shows how to generate an HTML and PDF report for a specific feature layer. It demonstrates how to create a report that includes summary statistics, photos, maps, and attribute infor
What do you think about this?

> In this example we are going to work with the `Trees` hosted feature layer that was deployed using this [ArcGIS Solution template](https://www.arcgis.com/apps/solutions/index.html?gallery=true&searchTerm=Tree%20Management&solution=vrrh5yvnj1b8ba2tkfab6kf36c2t18np).  Search for this layer in contents and copy and post the `item id` (found in the url) below where you see `<item-id>`

2025-01-23 18:01 UTC, lau13820 commented on notebooks/Generate PDF Report/Generate PDF Report.ipynb
> -    "This example shows how to generate an HTML and PDF report for a specific feature layer. It demonstrates how to create a report that includes summary statistics, photos, maps, and attribute infor
Perfect. Will add this. Thank you @jake-maps !

2025-01-23 18:33 UTC, jake-maps approved these changes

2025-01-23 19:43 UTC, merged